### ISSUE TITLE
Comprendre Steem mention tool fails to show mentions

### ISSUE THREAD

**Issue by littleboy0k** [Comprendre-Steem/api.comprendre-steem.fr#1]
#### Expected behavior
The steem based mention tool in http://api.comprendre-steem.fr/mentions/ is expected to show mentions of the username inputted.

#### Actual behavior
Fails to show any mentions or other information.

#### How to reproduce
1. Go to http://api.comprendre-steem.fr/mentions/
2. Input a valid steem username in the form.
3. The site then will fail to show any mentions of that username.

* Browser:  Google Chrome 61.0.3163.91 (Official Build) (64-bit)
* Operating system: Windows 7

**Comment by mktcode** [comment]
already fixed, can be closed
