### ISSUE TITLE
Wrong reputation calculation

### ISSUE THREAD

**Issue by RagePeanut** [Comprendre-Steem/api.comprendre-steem.fr#2]
This issue has been encountered while using Fast-Reply. As you can see below, the app gave a wrong reputation for the @checky account which has a reputation of exactly 25 (raw: 0). I first thought it came from the app but it turns out it actually comes from this api.
![](https://i.gyazo.com/d58606ee38bc43079616e786bde86664.png)

Another issue comes when an account has less than a raw 0 reputation. The account @a-0-0 for example should have a reputation of -7.91 but since its raw reputation is under 0, this api says its reputation is 0.
![](https://i.gyazo.com/f7702c8b3e56ac872430e807b8de639c.png)

**Comment by oroger** [comment]
Hum, good catch !
I noticed something was wrong with new accounts but did not went that far looking into an explaination yet.
Those data are retrieved using steemSQL, I have to check how the value is stored in there.

**Comment by oroger** [comment]
I found and fixed the error.
It was located in the [`getSimpleReputation`](https://github.com/Comprendre-Steem/api.comprendre-steem.fr/blob/master/sql/src/main/java/fr/comprendresteem/UnitConverter.java#L6-L12) function that transforms the raw reputation into a readable number.

Here is the first (read naive) implementation:
```	
public static double getSimpleReputation(long value) {
	double rep = (((Math.log10(value)) - 9) * 9) + 25;
	return Math.round(rep * 1000) / 1000.0;
}
```

Here is the fixed version using explaination from [@digitalnotvir](https://steemit.com/steemit/@digitalnotvir/how-reputation-scores-are-calculated-the-details-explained-with-simple-math) and js code from [steemJS](https://github.com/steemit/steem-js):

```
public static double getSimpleReputation(long value) {
	boolean neg = value < 0;
	double rep = Math.log10(Math.abs(value));
	rep = Math.max(rep - 9.0, 0.0);
	rep = (neg ? -1 : 1) * rep;
	rep = (rep * 9) + 25;
	return Math.round(rep * 1000) / 1000.0;
}
```

Here are the results for 

@roxane: 70.174 (104553894962739)
@ragepeanut: 60.6 (9027225078399)
@checky: 25 (0)
@a-0-0: -7.909 (-4534522956660)
